# Generated by Django 4.1.1 on 2022-12-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('upwd', models.CharField(max_length=16)),
                ('un', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
