# Generated by Django 4.1.1 on 2022-12-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_normaluser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('upwd', models.CharField(max_length=16)),
                ('un', models.CharField(max_length=16)),
            ],
        ),
    ]
