# Generated by Django 4.1.4 on 2022-12-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NormalUser',
        ),
    ]
